create table Person
(
    id         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name  varchar(100)                                         NOT NULL,
    yearOfBorn int CHECK ( yearOfBorn > 1930 AND yearOfBorn < 2025) NOT NULL,
    password   varchar                                              NOT NULL,
    role       varchar(100)                                         NOT NULL
);
